format = """
$username$hostname$directory$git_branch$git_status$git_commit$cmd_duration$fill$git_state$time
$character
"""


[git_branch]
style = 'bold bright-black'
format = 'on [$branch(:$remote_branch)]($style) '

[git_commit]
commit_hash_length = 7
style = 'bold blue'
format = '[\( $hash$tag\)]($style) '

[git_status]
format = '(\[[$all_status$ahead_behind]($style)\] )'
style = "white"
stashed = "[*](bold green)"
modified = "[!](bold yellow)"
deleted = "[-](bold red)"
conflicted = "[~](bold red)"
ahead = ">>"
behind = "<<"
untracked = "[?](bold yellow)"
staged = "[+](bold green)"

[git_state]
#style = "bold red"
#format = "[$state( $progress_current/$progress_total) ]($style)"
#rebase = "rebase"
#merge = "merge"
#revert = "revert"
#cherry_pick = "cherry"
#bisect = "bisect"
#am = "am"	
#am_or_rebase = "am/rebase"
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[character]
success_symbol = "[>>](bold green)"
error_symbol = "[>>](bold red)"
vimcmd_symbol = "[<](bold green)"

[hostname]
ssh_only = true
format = '[$ssh_symbol$hostname](bold green) in '
disabled = false

[username]
style_root = "bold red"
style_user = "bold cyan"
format = '[$user]($style) at '
show_always = false

[time]
disabled = false
style = 'bold black'
format =' [$time]($style) ' 
time_format = '%T'

[directory]
read_only = " 󰌾"
style = "bold blue"
repo_root_style = "bold blue"
truncation_length = 7
repo_root_format = '[$before_root_path]($style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '

[cmd_duration]
min_time = 500
format = 'took [$duration](bold purple) '

[fill]
symbol = " "
